#pragma once

// X-macro lists: (KEY, VALUE_INT)

#define APPUPDATE_ENUM_APP_UPDATE_TYPE(X) \
X(UNKNOWN, 0) \
X(FLEXIBLE, 1) \
X(IMMEDIATE, 2) \
X(SILENT, 3)

#define APPUPDATE_ENUM_INSTALL_ERROR_CODE(X) \
X(ERROR_UNKNOWN, 4001) \
X(ERROR_DOWNLOAD, 4002) \
X(ERROR_BLOCKED, 4003) \
X(ERROR_INVALID_APK, 4004) \
X(ERROR_CONFLICT, 4005) \
X(ERROR_STORAGE, 4006) \
X(ERROR_INCOMPATIBLE, 4007) \
X(ERROR_APP_NOT_OWNED, 4008) \
X(ERROR_INTERNAL_ERROR, 4009) \
X(ERROR_ABORTED, 4010) \
X(ERROR_APK_NOT_FOUND, 4011) \
X(ERROR_EXTERNAL_SOURCE_DENIED, 4012) \
X(ERROR_ACTIVITY_SEND_INTENT, 9901) \
X(ERROR_ACTIVITY_UNKNOWN, 9902)

#define APPUPDATE_ENUM_INSTALL_STATUS(X) \
X(UNKNOWN, 0) \
X(DOWNLOADED, 1) \
X(DOWNLOADING, 2) \
X(FAILED, 3) \
X(INSTALLING, 4) \
X(PENDING, 5)

#define APPUPDATE_ENUM_UPDATE_AVAILABILITY(X) \
X(UNKNOWN, 0) \
X(UPDATE_NOT_AVAILABLE, 1) \
X(UPDATE_AVAILABLE, 2) \
X(DEVELOPER_TRIGGERED_UPDATE_IN_PROGRESS, 3)

#define APPUPDATE_ENUM_UPDATE_FLOW_RESULT(X) \
X(RESULT_OK, -1) \
X(RESULT_CANCELED, 0) \
X(ACTIVITY_NOT_FOUND, 2)
